# Generated by Django 5.1.2 on 2024-11-05 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': ('Новости',),
                'ordering': ('-date',),
            },
        ),
    ]
